cluster: "$((INSTALDIR))/pbs-submit.py --depend \"{dependencies}\""
cluster-status: "$((INSTALDIR))/pbs-status.py"
jobscript: "$((INSTALDIR))/pbs-jobscript.sh"
jobs: 5000
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
